### ISSUE TITLE
Geting `ValueError: No regions found for ccan module 17.` with `Minimal_example.ipynb`

### ISSUE THREAD

**Issue by PetrKralCZ** [cantinilab/Circe#5]
Is the minimal example up to date? with `Circe-0.3.4` I am getting this error:
```
...
/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CIRCE/0.3.4-foss-2023a/lib/python3.11/site-packages/circe/circe.py:332: ImplicitModificationWarning: Setting element `.varp['atac_network']` of view, initializing view as actual.
  anndata.varp[key] = anndata.varp[key].tocoo()
Coaccessibility cutoff used: 0.02
Number of CCANs generated: 143
Coaccessibility cutoff used: 0.02
Coaccessibility cutoff used: 1e-07
Number of CCANs generated: 52
Traceback (most recent call last):
  File "/kyukon/home/gent/453/vsc45304/vsc-software-stack/409_CIRCE/run.py", line 86, in <module>
    ci.draw.plot_ccan(
  File "/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CIRCE/0.3.4-foss-2023a/lib/python3.11/site-packages/circe/draw.py", line 276, in plot_ccan
    raise ValueError(f"No regions found for ccan module {ccan_module}.")
ValueError: No regions found for ccan module 17.
```

**Comment by r-trimbour** [comment]
Hi !

The minimal example is still up to date, but the interesting CCAN modules might change depending on your seed.
You can plot your largest CCAN module as a test:
```
ccan_number = atac.var['CCAN'].value_counts().index[0]
ci.draw.plot_ccan(
    atac,
    ccan_module=ccan_number,
    sep=('_', '_'),
    abs_threshold=0,
    figsize=(15,5),
    only_positive=False)
```

The number are currently reflects the search process, that discard progressively some cluster. I'll rename it to the first integers in the next version to make it more intuitive ! :)

Rémi

**Comment by PetrKralCZ** [comment]
That worked. Thank you very much.
